baseURL = "https://alexandersandberg.com"
title = "alexandersandberg.com"

enableRobotsTXT = true
defaultContentLanguage = "en"
relativeURLs = true
disableKinds = ["taxonomy", "taxonomyTerm"]
enableEmoji = true

[permalinks]
	page = "/:slug/"
	posts = "/:slug/"

[params]
	googleAnalyticsId = "UA-29679247-2" # Uses the new gtag.js

[languages]
	[languages.en]
	lang = "en"
	languageName = "English"
	weight = 1

	[languages.sv]
	lang = "sv"
	languageName = "Svenska"
	weight = 2
