baseURL = "https://alexandersandberg.com"
title = "alexandersandberg.com"

enableRobotsTXT = true
defaultContentLanguage = "en"
relativeURLs = true
enableEmoji = true
disableKinds = ["taxonomy", "taxonomyTerm"]

[permalinks]
	page = "/:slug/"
	posts = "/:slug/"

[params]
	googleAnalyticsId = "UA-29679247-2" # Uses the new gtag.js

[blackfriday]
	hrefTargetBlank = true