baseURL = "https://alexandersandberg.com"
title = "Alexander Sandberg / alexandersandberg.com"

assetDir = "static"
enableRobotsTXT = true
defaultContentLanguage = "en"
relativeURLs = true
enableEmoji = true

[taxonomies]
	category = "categories"

[permalinks]
	pages = "/:slug/"
	posts = "/:slug/"
	categories = "/:slug/"

[params]
	googleAnalyticsId = "UA-29679247-2"
	metaDescription = "Self-taught Front-End Developer and Mobile Engineer with an MSc in Product Design, based in Linz, Austria. This is my personal website where I occasionally share some interesting stuff with the world."

[markup.goldmark.renderer]
	unsafe = true