[build]
  publish = "_site"
  command = "AWS_LAMBDA_FUNCTION_NAME=trickpuppeteer npm run build"

[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = false
[build.processing.js]
  bundle = true
  minify = false
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

[[plugins]]
package = "netlify-plugin-cache"

  [plugins.inputs]
  paths = [".cache"]