---
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: 
sections:
- type: heading
  label: Content
- type: directory
  path: content/posts
  label: Posts
  create: all
  match: "**/*"
  templates:
  - posts
  - books
- type: directory
  path: content/pages
  label: Pages
  create: all
  match: "**/*"
  templates:
  - pages
upload_dir: static/img
public_path: "/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.69.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server --minify
version: 0.69.0
