name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: swift run

      - name: Deploy
        uses: ayeressian/bunnycdn-storage-deploy@v2.2.1
        with:
          source: ".output"
          destination: ""
          storageZoneName: "${{ secrets.BUNNY_STORAGE_NAME }}"
          storagePassword: "${{ secrets.BUNNY_STORAGE_PASSWORD }}"
          accessKey: "${{ secrets.BUNNY_API_KEY }}"
          pullZoneId: "${{ secrets.BUNNY_PULL_ID }}"
          upload: "true"
          remove: "true"
          purgePullZone: "true"
